apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: screaming-morphs-staging-tls
  namespace: screaming-morphs-staging
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretName: screaming-morphs-staging-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - staging.screamingmorphs.com
