name: Ansible Lint

on:
  pull_request:
    paths:
      - 'ansible/**'
      - 'vms/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ansible-lint
        run: pipx run ansible-lint vms/
