apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aiostreams
  # NOTE: ArgoCD applications must be in the argocd namespace
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://forgejo.local:3000/tbtaylor100/infra.git
    targetRevision: main
    path: kubernetes/aiostreams
  destination:
    server: https://kubernetes.default.svc
    namespace: aiostreams
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
