apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    # kube-prometheus-stack Helm chart — https://github.com/prometheus-community/helm-charts
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "83.4.0"
    helm:
      values: |
        grafana:
          service:
            type: LoadBalancer
            annotations:
              metallb.universe.tf/loadBalancerIPs: "192.168.1.204"

        prometheus:
          prometheusSpec:
            additionalScrapeConfigs:
              - job_name: proxmox-node
                static_configs:
                  - targets:
                      - 192.168.1.12:9100
              - job_name: homelab-vm102
                static_configs:
                  - targets:
                      - 192.168.1.50:9100

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
