apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: screaming-morphs-production
    # NOTE: ArgoCD applications must be in the argocd namespace
  namespace: argocd
spec:
  project: default
  source:
    # Custom apps manage namepsace + ExternalSecret in infra repo, not app repo
    repoURL: http://forgejo.local:3000/tbtaylor100/infra.git
    targetRevision: main
    path: kubernetes/screaming-morphs/production
  destination:
    server: https://kubernetes.default.svc
    namespace: screaming-morphs-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true