apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: screaming-morphs-production-app
  # NOTE: ArgoCD applications must be in the argocd namespace
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://forgejo.local:3000/tbtaylor100/screaming_morphs.git
    targetRevision: main
    path: helm/screaming-morphs
    helm:
      valueFiles:
        - values/production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: screaming-morphs-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

