apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: screaming-morphs-production-secret
  namespace: screaming-morphs-production
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: screaming-morphs-production-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: screaming-morphs/production/environment
