apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel-secret
  namespace: screaming-morphs-production
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: cloudflared-tunnel-secret
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: screaming-morphs/production/cloudflare-tunnel
        property: credentials
