apiVersion: v1
kind: ConfigMap
metadata:
  name: aiostreams-config
  namespace: aiostreams
data:
  WHITELISTED_REGEX_PATTERNS: '["/(?:WEB-DL|AMZN|DSNP|YTS|RARBG|EZTV)/i"]'
  REGEX_FILTER_ACCESS: "all"
  PORT: "3000"
  ANIME_DB_LEVEL_OF_DETAIL: "none"
