apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aiostreams-secret
  namespace: aiostreams
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: aiostreams-secret
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: aiostreams/production
        property: SECRET_KEY
    - secretKey: FORCED_SERVICE_CREDENTIALS
      remoteRef:
        key: aiostreams/production
        property: FORCED_SERVICE_CREDENTIALS
